name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest    

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Setu up node  
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn

