name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest    

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Setu up node  
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn build
      - run: echo "Staring tests"
      - run: yarn test
      - run: yarn test:e2e
      - 
      use jest-junit reporter)
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: jest-junit.xml
